import { StoreData } from "./store";

const SEED_GROUP_ID = "seed-group-001";
const SEED_MEMBER_ID = "seed-member-001";
const SEED_CITY_ID = "seed-city-dali";

export const SEED_DATA: StoreData = {
  currentGroupId: SEED_GROUP_ID,
  currentMemberId: SEED_MEMBER_ID,
  groups: [
    {
      id: SEED_GROUP_ID,
      name: "云南之旅",
      invite_code: "DALI26",
      created_at: "2026-04-01T00:00:00Z",
    },
  ],
  members: [
    {
      id: SEED_MEMBER_ID,
      group_id: SEED_GROUP_ID,
      nickname: "Sophie",
      is_owner: true,
      created_at: "2026-04-01T00:00:00Z",
    },
  ],
  cities: [
    {
      id: SEED_CITY_ID,
      group_id: SEED_GROUP_ID,
      name: "大理 Dali",
      center_lat: 25.6065,
      center_lng: 100.2676,
      center_lat_gcj: null,
      center_lng_gcj: null,
      dates_start: "2026-05-10",
      dates_end: "2026-05-20",
      sort_order: 0,
      stay_name: "大理古城民宿",
      stay_address: "大理古城人民路 42号",
      stay_lat: 25.6897,
      stay_lng: 100.1648,
      stay_lat_gcj: null,
      stay_lng_gcj: null,
      stay_checkin: "2026-05-10",
      stay_checkout: "2026-05-20",
      created_at: "2026-04-01T00:00:00Z",
    },
  ],
  places: [
    {
      id: "place-001",
      city_id: SEED_CITY_ID,
      added_by: SEED_MEMBER_ID,
      name: "再回首凉鸡米线",
      category: "noodles",
      priority: "must_go",
      lat: 25.6901,
      lng: 100.1645,
      lat_gcj: null,
      lng_gcj: null,
      address: "大理古城人民路 1号",
      payment: ["wechat_pay", "alipay", "cash"],
      hours_note: "早上7点到下午3点，卖完即止",
      reservation_required: false,
      reservation_url: null,
      notes: "大理最有名的米线店，凉鸡米线是招牌。早点去排队少。",
      summary: "必吃！凉鸡米线+卤鸡皮，早上去避开人流。",
      created_at: "2026-04-01T00:00:00Z",
    },
    {
      id: "place-002",
      city_id: SEED_CITY_ID,
      added_by: SEED_MEMBER_ID,
      name: "杨记烤乳扇",
      category: "street_food",
      priority: "must_go",
      lat: 25.6905,
      lng: 100.1640,
      lat_gcj: null,
      lng_gcj: null,
      address: "大理古城复兴路",
      payment: ["wechat_pay", "alipay", "cash"],
      hours_note: "全天营业",
      reservation_required: false,
      reservation_url: null,
      notes: "烤乳扇是大理特色，玫瑰酱口味最经典。",
      summary: "烤乳扇选玫瑰酱味，10块一个。",
      created_at: "2026-04-01T01:00:00Z",
    },
    {
      id: "place-003",
      city_id: SEED_CITY_ID,
      added_by: SEED_MEMBER_ID,
      name: "石井私房菜",
      category: "dinner",
      priority: "must_go",
      lat: 25.6890,
      lng: 100.1650,
      lat_gcj: null,
      lng_gcj: null,
      address: "大理古城博爱路 99号",
      payment: ["wechat_pay", "alipay"],
      hours_note: "11:00-14:00, 17:00-21:00",
      reservation_required: true,
      reservation_url: null,
      notes: "本地人推荐的私房菜，酸辣鱼必点。提前一天预约。",
      summary: "酸辣鱼 + 老奶洋芋 + 水性杨花，提前预约。",
      created_at: "2026-04-01T02:00:00Z",
    },
    {
      id: "place-004",
      city_id: SEED_CITY_ID,
      added_by: SEED_MEMBER_ID,
      name: "海稍鱼·翠田餐厅",
      category: "lunch",
      priority: "want_to",
      lat: 25.5900,
      lng: 100.2200,
      lat_gcj: null,
      lng_gcj: null,
      address: "大理市下关镇洱海边",
      payment: ["wechat_pay", "alipay"],
      hours_note: "11:00-21:00",
      reservation_required: false,
      reservation_url: null,
      notes: "洱海边吃鱼，环境好。海稍鱼是洱海特色做法。",
      summary: "洱海边景观位吃海稍鱼，人均80。",
      created_at: "2026-04-01T03:00:00Z",
    },
    {
      id: "place-005",
      city_id: SEED_CITY_ID,
      added_by: SEED_MEMBER_ID,
      name: "喜洲粑粑·和尚老铺",
      category: "breakfast",
      priority: "must_go",
      lat: 25.7330,
      lng: 100.1480,
      lat_gcj: null,
      lng_gcj: null,
      address: "喜洲古镇四方街",
      payment: ["wechat_pay", "cash"],
      hours_note: "早上8点开始，下午卖完收摊",
      reservation_required: false,
      reservation_url: null,
      notes: "喜洲粑粑是大理传统小吃，甜咸两种口味，咸味更好。",
      summary: "咸味粑粑 > 甜味，刚出炉的最好吃。",
      created_at: "2026-04-01T04:00:00Z",
    },
    {
      id: "place-006",
      city_id: SEED_CITY_ID,
      added_by: SEED_MEMBER_ID,
      name: "大理古城人民路 Bad Monkey",
      category: "cafe",
      priority: "want_to",
      lat: 25.6895,
      lng: 100.1643,
      lat_gcj: null,
      lng_gcj: null,
      address: "大理古城人民路上段",
      payment: ["wechat_pay", "alipay"],
      hours_note: "9:00-22:00",
      reservation_required: false,
      reservation_url: null,
      notes: "人民路上很有氛围的咖啡店，可以坐很久。",
      summary: null,
      created_at: "2026-04-01T05:00:00Z",
    },
    {
      id: "place-007",
      city_id: SEED_CITY_ID,
      added_by: SEED_MEMBER_ID,
      name: "巍山耙肉饵丝",
      category: "breakfast",
      priority: "want_to",
      lat: 25.6903,
      lng: 100.1638,
      lat_gcj: null,
      lng_gcj: null,
      address: "大理古城玉洱路",
      payment: ["wechat_pay", "alipay", "cash"],
      hours_note: "早上6:30-下午2:00",
      reservation_required: false,
      reservation_url: null,
      notes: "耙肉饵丝是巍山特色，肉炖得很烂，汤头鲜。",
      summary: "加个卤蛋，汤要多要。",
      created_at: "2026-04-01T06:00:00Z",
    },
    {
      id: "place-008",
      city_id: SEED_CITY_ID,
      added_by: SEED_MEMBER_ID,
      name: "大理老木瓜鸡",
      category: "dinner",
      priority: "want_to",
      lat: 25.6888,
      lng: 100.1655,
      lat_gcj: null,
      lng_gcj: null,
      address: "大理古城洋人街附近",
      payment: ["wechat_pay", "alipay"],
      hours_note: "11:00-21:30",
      reservation_required: false,
      reservation_url: null,
      notes: "木瓜鸡是白族特色菜，酸酸甜甜很开胃。",
      summary: null,
      created_at: "2026-04-01T07:00:00Z",
    },
    {
      id: "place-009",
      city_id: SEED_CITY_ID,
      added_by: SEED_MEMBER_ID,
      name: "Serendipity 甜品店",
      category: "dessert",
      priority: "if_time",
      lat: 25.6898,
      lng: 100.1646,
      lat_gcj: null,
      lng_gcj: null,
      address: "大理古城人民路中段",
      payment: ["wechat_pay", "alipay"],
      hours_note: "10:00-21:00",
      reservation_required: false,
      reservation_url: null,
      notes: "很多博主推荐的甜品店，芒果糯米饭好看好吃。",
      summary: null,
      created_at: "2026-04-01T08:00:00Z",
    },
    {
      id: "place-010",
      city_id: SEED_CITY_ID,
      added_by: SEED_MEMBER_ID,
      name: "大理白族三道茶体验",
      category: "tea_house",
      priority: "want_to",
      lat: 25.7340,
      lng: 100.1475,
      lat_gcj: null,
      lng_gcj: null,
      address: "喜洲严家大院",
      payment: ["wechat_pay", "alipay", "cash"],
      hours_note: "9:00-17:00",
      reservation_required: false,
      reservation_url: null,
      notes: "白族三道茶：一苦二甜三回味。喜洲严家大院的体验最正宗。",
      summary: "在严家大院体验三道茶+白族歌舞，门票含茶。",
      created_at: "2026-04-01T09:00:00Z",
    },
  ],
  sources: [
    {
      id: "source-001",
      place_id: "place-001",
      added_by: SEED_MEMBER_ID,
      platform: "rednote",
      url: "https://www.xiaohongshu.com/explore/dali-mixi-001",
      author: "@云南吃货日记",
      caption: "大理古城必吃！这家凉鸡米线排队1小时也值得",
      key_takeaway: "凉鸡米线+卤鸡皮，早上10点前去不用排队",
      rating_vibe: "loved",
      screenshot_url: null,
      added_at: "2026-04-01T00:00:00Z",
    },
    {
      id: "source-002",
      place_id: "place-001",
      added_by: SEED_MEMBER_ID,
      platform: "tiktok",
      url: "https://www.tiktok.com/@dali_foodie/video/123456",
      author: "@dali_foodie",
      caption: "The most famous noodle shop in Dali Old Town",
      key_takeaway: "点小份就够了，加辣更好吃",
      rating_vibe: "recommended",
      screenshot_url: null,
      added_at: "2026-04-02T00:00:00Z",
    },
    {
      id: "source-003",
      place_id: "place-001",
      added_by: SEED_MEMBER_ID,
      platform: "rednote",
      url: "https://www.xiaohongshu.com/explore/dali-mixi-002",
      author: "@旅行的小鱼",
      caption: "再回首的秘密菜单！除了米线还有这些",
      key_takeaway: "隐藏菜单：鸡皮凉片，不在墙上菜单里要自己问",
      rating_vibe: "loved",
      screenshot_url: null,
      added_at: "2026-04-03T00:00:00Z",
    },
    {
      id: "source-004",
      place_id: "place-003",
      added_by: SEED_MEMBER_ID,
      platform: "rednote",
      url: "https://www.xiaohongshu.com/explore/dali-shiijng-001",
      author: "@大理本地通",
      caption: "大理本地人才知道的私房菜馆",
      key_takeaway: "酸辣鱼用的是洱海鱼，老奶洋芋也是招牌",
      rating_vibe: "loved",
      screenshot_url: null,
      added_at: "2026-04-01T02:00:00Z",
    },
    {
      id: "source-005",
      place_id: "place-005",
      added_by: SEED_MEMBER_ID,
      platform: "rednote",
      url: "https://www.xiaohongshu.com/explore/dali-baba-001",
      author: "@喜洲古镇攻略",
      caption: "喜洲粑粑哪家最正宗？本地人都来这家",
      key_takeaway: "认准和尚老铺，咸味的比甜味好吃",
      rating_vibe: "loved",
      screenshot_url: null,
      added_at: "2026-04-01T04:00:00Z",
    },
    {
      id: "source-006",
      place_id: "place-002",
      added_by: SEED_MEMBER_ID,
      platform: "instagram",
      url: "https://www.instagram.com/p/dali-rushan-001",
      author: "@yunnan.eats",
      caption: "Grilled milk fan cake with rose jam 🌹",
      key_takeaway: "玫瑰酱味最经典，拍照也好看",
      rating_vibe: "recommended",
      screenshot_url: null,
      added_at: "2026-04-01T01:00:00Z",
    },
    {
      id: "source-007",
      place_id: "place-009",
      added_by: SEED_MEMBER_ID,
      platform: "rednote",
      url: "https://www.xiaohongshu.com/explore/dali-dessert-001",
      author: "@甜品探店",
      caption: "大理古城最出片的甜品店",
      key_takeaway: "芒果糯米饭颜值高，味道一般般，主要是拍照",
      rating_vibe: "mixed",
      screenshot_url: null,
      added_at: "2026-04-01T08:00:00Z",
    },
    {
      id: "source-008",
      place_id: "place-004",
      added_by: SEED_MEMBER_ID,
      platform: "tiktok",
      url: "https://www.tiktok.com/@yunnan_travel/video/789012",
      author: "@yunnan_travel",
      caption: "洱海边最好吃的鱼！海稍鱼到底有多鲜",
      key_takeaway: "选靠窗位看洱海，鱼是当天捞的",
      rating_vibe: "loved",
      screenshot_url: null,
      added_at: "2026-04-01T03:00:00Z",
    },
  ],
  dayPlans: [
    {
      id: "day-001",
      city_id: SEED_CITY_ID,
      date: "2026-05-10",
      label: "Day 1 — 大理古城探店",
      sort_order: 0,
    },
    {
      id: "day-002",
      city_id: SEED_CITY_ID,
      date: "2026-05-11",
      label: "Day 2 — 喜洲 + 洱海",
      sort_order: 1,
    },
  ],
  dayPlanStops: [
    {
      id: "stop-001",
      day_plan_id: "day-001",
      place_id: "place-001",
      sort_order: 0,
      arrival_time: "09:00",
      notes: "早点去排队少",
    },
    {
      id: "stop-002",
      day_plan_id: "day-001",
      place_id: "place-002",
      sort_order: 1,
      arrival_time: null,
      notes: null,
    },
    {
      id: "stop-003",
      day_plan_id: "day-001",
      place_id: "place-006",
      sort_order: 2,
      arrival_time: "14:00",
      notes: "下午咖啡时间",
    },
    {
      id: "stop-004",
      day_plan_id: "day-001",
      place_id: "place-003",
      sort_order: 3,
      arrival_time: "18:00",
      notes: "记得提前预约！",
    },
    {
      id: "stop-005",
      day_plan_id: "day-002",
      place_id: "place-005",
      sort_order: 0,
      arrival_time: "08:30",
      notes: null,
    },
    {
      id: "stop-006",
      day_plan_id: "day-002",
      place_id: "place-010",
      sort_order: 1,
      arrival_time: "10:00",
      notes: null,
    },
    {
      id: "stop-007",
      day_plan_id: "day-002",
      place_id: "place-004",
      sort_order: 2,
      arrival_time: "12:00",
      notes: "从喜洲开车去洱海边",
    },
  ],
};
